/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg3hge;

import java.awt.Color;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modular.OpapJokerDraws;
import org.json.simple.parser.ParseException;

/**
 *
 * @author Giorg
 */
public class DataManagement extends javax.swing.JFrame {
    
            OpapJokerDraws draw;
           LastResultPull singledate = new LastResultPull();         //pull information from api
           SaveCompare saved = new SaveCompare();
           DeleteDraw deleted = new DeleteDraw();
           DrawbyDate muldates = new DrawbyDate();
           ArrayList<OpapJokerDraws> muldraw;
    
           
    
    public DataManagement() {
         
        
        
        initComponents();
         this.getContentPane().setBackground(new Color(0x123456));
         ImageIcon image = new ImageIcon("src/opap.jpg");
        this.setIconImage(image.getImage());
        this.setLocationRelativeTo(null);
        
        
        
        
        jButton1.setEnabled(false);
         
           jButton3.setEnabled(false);
           jLabel20.setVisible(false);
    }
    
    
       
           
           
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setTitle("Διαχείρηση Δεδομένων ΤΖΟΚΕΡ");
        setBackground(new java.awt.Color(255, 255, 0));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Παιχνίδια εντός εύρους ημερομηνιών");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Τυχεροί αριθμοί:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Webp.net-resizeimage.png"))); // NOI18N
        jButton1.setText("Διαγραφή Δεδομένων Παιχνιδιού");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Webp.net-resizeimage.png"))); // NOI18N
        jButton2.setText("Διαγραφή Δεδομένων παιχνιδιών εντός εύρους ημερομηνιών");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        jButton3.setText("Αποθήκευση Δεδομένων");
        jButton3.setName(""); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton4.setText("Επιλογή");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID Μεμονομένου Παιχνιδιού");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Από:");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Εώς");

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setBorder(null);
        jTextField2.setOpaque(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton5.setText("Επιλογή");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTable2.setForeground(new java.awt.Color(0, 0, 0));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Διανεμόμενα", "Επιτυχίες", "Κέρδη ανά Επιτυχία"
            }
        ));
        jTable2.setRowHeight(21);
        jScrollPane2.setViewportView(jTable2);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ΤΖΟΚΕΡ");

        jTextField3.setBackground(new java.awt.Color(217, 158, 21));
        jTextField3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(213, 109, 30));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setBorder(null);
        jTextField3.setOpaque(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(0, 0, 204));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("5+1");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("5");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("4+1");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("4");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("3+1");

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("3");

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("2+1");

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("1+1");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        jButton6.setText("Αποθήκευση Όλων εντός ημερομηνιών");
        jButton6.setFocusable(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Επιλέξατε την κλήρωση:");

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("ΔΕΝ ΕΧΕΤΕ ΕΠΙΛΕΞΕΙ ΚΛΗΡΩΣΗ");
        jTextField4.setOpaque(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel21.setText("Επιλέξτε παιχνίδια εντώς 3 μηνών. Για μεγαλύτερα χρονικά διαστήματα, εκτελέστε πολλαπλές αποθηκέυσεις.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(244, 244, 244))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(227, 227, 227)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel12)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(jLabel13))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel15)))
                                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel17)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(82, 82, 82)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(173, 173, 173))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(jButton1))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jButton4)))
                        .addGap(131, 131, 131)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(207, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jButton5)
                        .addGap(314, 314, 314))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(429, 429, 429))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(318, 318, 318))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel2)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)))
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        String drawIDtodelete = jTextField1.getText();
        int drawIDtodeleteint = Integer.parseInt(drawIDtodelete);
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("3hGEPU");
        EntityManager em = emf.createEntityManager();
        
    
           
            if ( saved.compareResult(drawIDtodeleteint, em) == true ){
                int Yes =  JOptionPane.showConfirmDialog(null,"Η κλήρωση με ID "+drawIDtodeleteint+ " θα διαγραφεί. Είστε σίγουροι;","Προσοχή!",JOptionPane.YES_NO_OPTION);
                if (Yes == JOptionPane.YES_OPTION){
                 deleted.deleteDrawID(drawIDtodeleteint); 
                   JOptionPane.showMessageDialog(null,"Η κλήρωση με  ID"+drawIDtodeleteint+" έχει διαγραφεί.");
                 
                }         
            }
        else {
           JOptionPane.showMessageDialog(null, "Η κλήρωση με ID "+drawIDtodeleteint+" δεν είναι αποθηκευμένη στο σύστημα!", "Προσοχή.", JOptionPane.INFORMATION_MESSAGE);
        }
            
            
            
            
            
            
            
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        
        
         SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        String sd = dateFormat.format(jDateChooser1.getDate());
        String ed = dateFormat.format(jDateChooser2.getDate());
      
         
         SimpleDateFormat view = new SimpleDateFormat("dd-MM-yyyy");
         
         String vsd = view.format(jDateChooser1.getDate());
         String ved = view.format(jDateChooser2.getDate());
         
         
                try {
                    muldraw =   muldates.DrawbyDate(sd, ed, 5104);
                } catch (ParseException | IOException ex) {
                    Logger.getLogger(DataManagement.class.getName()).log(Level.SEVERE, null, ex);
                }
           
            
      
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("3hGEPU");
        EntityManager em = emf.createEntityManager();
        
             Object[] options = { "Ναι", "Όχι" };
             
             
             
             
         int Yes =  JOptionPane.showOptionDialog(null,"Οι κληρώσεις απο "+vsd+ " εώς "+ved+" θα διαγραφούν. Είστε σίγουροι;","Προσοχή!",JOptionPane.INFORMATION_MESSAGE,JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
        

               if (Yes == JOptionPane.YES_OPTION){   
               for (OpapJokerDraws datedraw : muldraw) {
           
              if ( saved.compareResult(datedraw.getDrawid(), em) == true ){
             
                deleted.deleteDrawID(datedraw.getDrawid()); 
                }         
            
        else {
           JOptionPane.showMessageDialog(null, "Η κλήρωση με ID "+datedraw.getDrawid()+" δεν είναι αποθηκευμένη στο σύστημα!", "Προσοχή.", JOptionPane.INFORMATION_MESSAGE);
        }
            
        }
        }
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        
        String drawIDtocompare = jTextField1.getText();
        int drawIDtodcompareint = Integer.parseInt(drawIDtocompare);
        
          System.out.println("aaaaa");
          
            if (jTextField1.getText().equals(null))
            
      {
          JOptionPane.showMessageDialog(null,"Εισάγετε αριθμό κλήρωσης"/*+checkLatest()*/,"Προσοχή!", JOptionPane.OK_OPTION,null);
      }
 
       EntityManagerFactory emf = Persistence.createEntityManagerFactory("3hGEPU");
       EntityManager em = emf.createEntityManager();
       
     
    
       
       
  
        
        if ( saved.compareResult(drawIDtodcompareint, em) == true )
        {
            Object[] options = { "Ναι", "Όχι" };
            
              int Yes =  JOptionPane.showOptionDialog(null,"Η κλήρωση με ID "+drawIDtodcompareint+ " υπάρχει ήδη. Θέλετε να διαγραφεί; ","Προσοχή!", JOptionPane.INFORMATION_MESSAGE,JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
                if (Yes == JOptionPane.YES_OPTION)
                {
                   String drawIDtodel = drawIDtocompare;
                    int drawIDtodelete2int = Integer.parseInt(drawIDtodel);
                    deleted.deleteDrawID(drawIDtodelete2int);
                    JOptionPane.showMessageDialog(null,"Η κλήρωση με  ID"+drawIDtodelete2int+" έχει διαγραφεί.");
                }
                        
        }
        else {
           saved.saveResult(draw);
            JOptionPane.showMessageDialog(null, "Το ID αποθηκεύτηκε", "Επιτυχία.", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
        
        
      
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        if (jTextField1.getText().equals("")){
  
                JOptionPane.showMessageDialog(null,"Εισάγετε αριθμό κλήρωσης"/*+checkLatest()*/,"Προσοχή!", JOptionPane.OK_OPTION,null);
         
}
        else {
        jButton1.setEnabled(true);
         jButton2.setEnabled(true);
          jButton6.setEnabled(true);
           jButton3.setEnabled(true);
        jLabel20.setVisible(true);
        
        DefaultTableModel tblMod = (DefaultTableModel)jTable2.getModel();
        
        tblMod.setRowCount(0);
        
        
        String drawID  = jTextField1.getText();
        jTextField4.setText(jTextField1.getText());
        
        
       
           int drawIDint = Integer.parseInt(drawID);
        try {
            draw = singledate.DrawByID(drawIDint, 5104);
        } catch (ParseException | IOException ex) {
            Logger.getLogger(DataManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
          
           
          jTextField2.setText(draw.getWinnningnumbers());
          String joker = String.valueOf(draw.getBonusnumber());

          jTextField3.setText(joker);
          
           String[] dividentArray = draw.getDivident().split(",");
           String[] distributedArray = draw.getDistributed().split(",");
           String[] countWinnersArray = draw.getCountwinners().split(",");
           
           
            
      
        
         
          for (int i = 0; i < 8; i++) {
            tblMod.addRow(new Object[]{distributedArray[i], countWinnersArray[i], dividentArray[i]});
             }
         
          
          
        }
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        
       Date today = new Date();
       
        System.out.println(jDateChooser1.getDate());
       
    if  ( jDateChooser1.getDate() == null || jDateChooser2.getDate() == null )
    {
             JOptionPane.showMessageDialog(null,"Εισάγετε κάποια ημερομηνία.","Προσοχή!", JOptionPane.OK_OPTION,null);
    }
        
    if (jDateChooser1.getDate().compareTo(jDateChooser2.getDate()) > 0 )
    {
     JOptionPane.showMessageDialog(null,"Εισάγετε ημερομηνία Από μικρότερη απο Εώς.","Προσοχή!", JOptionPane.OK_OPTION,null);
    
    }
     if (jDateChooser1.getDate().compareTo(jDateChooser2.getDate()) == 0 )
    {
     JOptionPane.showMessageDialog(null,"Εισάγετε ημερομηνία Από μικρότερη απο Εώς.","Προσοχή!", JOptionPane.OK_OPTION,null);
    
    }
     
    
      if (jDateChooser2.getDate().compareTo(today) > 0)
      {
     JOptionPane.showMessageDialog(null,"Η ημερομηνία δεν μπορεί να είναι μελλοντική...","Προσοχή!", JOptionPane.OK_OPTION,null);
    
     }if (jDateChooser1.getDate().compareTo(today) > 0)
      {
     JOptionPane.showMessageDialog(null,"Η ημερομηνία δεν μπορεί να είναι μελλοντική...","Προσοχή!", JOptionPane.OK_OPTION,null);
    
     }
      
      
      
        
      
        String sd = dateFormat.format(jDateChooser1.getDate());
        String ed = dateFormat.format(jDateChooser2.getDate());
        
     
        
         SimpleDateFormat popupdate = new SimpleDateFormat("dd-MM-yyyy");
         
        try {
            muldraw =   muldates.DrawbyDate(sd, ed, 5104);
           
             for (OpapJokerDraws datedraw : muldraw) {
                       
                 String cd = popupdate.format(datedraw.getDrawtime());
                 
                  Object[] options = { "Ναι", "Όχι" };
         
                    
              if( JOptionPane.showOptionDialog(this,"Η κλήρωση είχε κωδικό " +datedraw.getDrawid() + " θέλετε να δείτε περισσότερες πληροφορίες;","Ημερομηνία κλήρωσης: " +cd+ "", JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE,null,options,options[0] ) == JOptionPane.YES_OPTION ) {
                  
            
                     FurtherInfo pnl = new FurtherInfo();
                      pnl.setVisible(true);
                       
                               
                      int drawint = datedraw.getDrawid();
                         String drawintstring = String.valueOf(drawint);
                                 
                        pnl.jTextField3.setText(drawintstring);        
                           
                        
                                          
                           
                     } 
              

        }
                     } catch (ParseException | IOException ex) {
            Logger.getLogger(DataManagement.class.getName()).log(Level.SEVERE, null, ex);
                         }

              
       
         
         
          
         
         
         
       
         
         
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
  
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        String sd = dateFormat.format(jDateChooser1.getDate());
        String ed = dateFormat.format(jDateChooser2.getDate());
      
         
         SimpleDateFormat view = new SimpleDateFormat("dd-MM-yyyy");
         
         String vsd = view.format(jDateChooser1.getDate());
         String ved = view.format(jDateChooser2.getDate());
         
         
                try {
                    muldraw =   muldates.DrawbyDate(sd, ed, 5104);
                } catch (ParseException | IOException ex) {
                    Logger.getLogger(DataManagement.class.getName()).log(Level.SEVERE, null, ex);
                }
           
            
      
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("3hGEPU");
        EntityManager em = emf.createEntityManager();
        
             Object[] options = { "Ναι", "Όχι" };
             
             
             
             
         int Yes =  JOptionPane.showOptionDialog(null,"Οι κληρώσεις απο "+vsd+ " εώς "+ved+" θα αποθηκευτούν. Είστε σίγουροι;","Προσοχή!",JOptionPane.INFORMATION_MESSAGE,JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
        

               if (Yes == JOptionPane.YES_OPTION){   
               for (OpapJokerDraws datedraw : muldraw) {
                       int tot = muldraw.size();
                            if ( saved.compareResult(datedraw.getDrawid(), em) == false ){
                            for (int i =0; i<tot; i++){
                                saved.saveResult(muldraw.get(i));}
                              }         
                                                              
            
           
           
   
                  
            
                                                        }
               
               JOptionPane.showMessageDialog(null, "Οι κληρώσεις έχουν αποθηκευτεί.", "Επιτυχία.", JOptionPane.INFORMATION_MESSAGE);
               
                                                }               
        
               
        
            }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataManagement().setVisible(true);
            }
        });
    }
    
    
   /*  public int checkLatest() throws ParseException, IOException {
            

        String urlStatistics = "https://api.opap.gr/draws/v3.0/5104/last-result-and-active";
        OkHttpClient client = new OkHttpClient();

        Request request = new Request.Builder().url(urlStatistics).build();

        try (Response response = client.newCall(request).execute()) {
            if (response.isSuccessful() && response.body() != null) {
                String responseString = response.body().string();
                JSONParser jsonparser = new JSONParser();
                Object mainObj = jsonparser.parse(responseString);
                JSONObject mainJSONObj = (JSONObject) mainObj;
                int drawId = (int) mainJSONObj.get("drawId");
                
                
                
                

                
                
                System.out.println(drawId);
              
         
        
              return 1;

                
            }
            
        } catch (IOException e) {
            e.printStackTrace();
        }
        return 0;
         
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
