/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg3hge;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.ImageIcon;
import modular.OpapJokerDraws;


/**
 *
 * @author Giorg
 */
public class DataDisplaybyMonth extends javax.swing.JFrame {

    
    
            OpapJokerDraws draw;
 
           LastResultPull singledate = new LastResultPull();         //pull information from api
           SaveCompare saved = new SaveCompare();
           DeleteDraw deleted = new DeleteDraw();
           DrawbyDate muldates = new DrawbyDate();
           ArrayList<OpapJokerDraws> muldraw;
           EntityManagerFactory emf = Persistence.createEntityManagerFactory("3hGEPU");
           EntityManager em = emf.createEntityManager();
           
           
           
           
           
           
           
           
           
           
           
           
           

    /**
     * Creates new form Option2
     */
    public DataDisplaybyMonth() {
        initComponents();
           this.getContentPane().setBackground(new Color(0x123456));
        ImageIcon image = new ImageIcon("src/opap.jpg");
        this.setIconImage(image.getImage());
       this.setLocationRelativeTo(null);
       
       
       
       
       
       
        
        jButton4.setEnabled(false);
         jButton2.setEnabled(false);
          jButton6.setEnabled(false);
           jButton3.setEnabled(false);
       
        jButton5.setEnabled(false);
         jButton7.setEnabled(false);
          jButton8.setEnabled(false);
           jButton9.setEnabled(false);
           
        jButton10.setEnabled(false);
         jButton11.setEnabled(false);
        jButton12.setEnabled(false);
         jButton13.setEnabled(false);
       
       
       
       
       
       
       
       
       
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Προβολή Δεδομένων ΤΖΟΚΕΡ ανά μήνα για συγκεκριμένο Έτος");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Έχετε επιλέξει το Έτος:");
        jLabel1.setToolTipText("");

        jButton1.setText("Επιλογή");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022" }));

        jButton2.setText("Φεβρουάριος");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ιανουάριος");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Απρίλιος");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Μάρτιος");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Ιούνιος");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Μάιος");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Αύγουστος");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Ιούλιος");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Νοέμβριος");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Δεκέμβριος");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Σεπτέμβριος");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Οκτώβριος");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton7)
                                        .addGap(53, 53, 53)
                                        .addComponent(jButton6)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton12)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton11))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton9)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton8))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel1)
                        .addGap(46, 46, 46)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(292, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13)
                    .addComponent(jButton12)
                    .addComponent(jButton11)
                    .addComponent(jButton10))
                .addContainerGap(184, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String cbtext = String.valueOf(jComboBox2.getSelectedItem());
        jTextField2.setText(cbtext);
        
        
       
        
            jButton7.setEnabled(true);
             jButton6.setEnabled(true);
             jButton4.setEnabled(true);
           jButton11.setEnabled(true);
          jButton12.setEnabled(true);
          jButton13.setEnabled(true);
          jButton8.setEnabled(true);
           jButton9.setEnabled(true);
           jButton10.setEnabled(true);
                 jButton2.setEnabled(true);
         
           jButton3.setEnabled(true);
       
        jButton5.setEnabled(true);
       
        
      
          
           
        
        
       
         
    int cbextin = Integer.parseInt(cbtext);
        
        if (cbextin == 2022)
            
        {
         
            jButton7.setEnabled(false);
             jButton6.setEnabled(false);
             jButton4.setEnabled(false);
           jButton11.setEnabled(false);
          jButton12.setEnabled(false);
          jButton13.setEnabled(false);
          jButton8.setEnabled(false);
           jButton9.setEnabled(false);
           jButton10.setEnabled(false);
            
        }
        else {
     
        } 
            
        //έλεγχος ημερομηνίας
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      
             
       SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String cbtext = String.valueOf(jComboBox2.getSelectedItem());
    
        
        
              
                InfoByMonth pnl = new InfoByMonth();
                      pnl.setVisible(true);
                       
                               
                      String year = cbtext;
                      pnl.jTextField1.setText(cbtext);        
                           
                      String month = "Ιανουάριος";
                      pnl.jTextField2.setText(month);
        
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
            
       SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String cbtext = String.valueOf(jComboBox2.getSelectedItem());
    
        
        
              
                InfoByMonth pnl = new InfoByMonth();
                      pnl.setVisible(true);
                       
                               
                      String year = cbtext;
                      pnl.jTextField1.setText(cbtext);        
                      
                      
                      
                         String month = "Μάιος";
                      pnl.jTextField2.setText(month);
                           
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
             
       SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String cbtext = String.valueOf(jComboBox2.getSelectedItem());
    
        
        
              
                InfoByMonth pnl = new InfoByMonth();
                      pnl.setVisible(true);
                       
                               
                      String year = cbtext;
                      pnl.jTextField1.setText(cbtext);        
                      
                      
                         String month = "Σεπτέμβριος";
                      pnl.jTextField2.setText(month);
                           
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
             
       SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String cbtext = String.valueOf(jComboBox2.getSelectedItem());
    
        
        
              
                InfoByMonth pnl = new InfoByMonth();
                      pnl.setVisible(true);
                       
                               
                      String year = cbtext;
                      pnl.jTextField1.setText(cbtext);     
                      
                       String month = "Φεβρουάριος";
                      pnl.jTextField2.setText(month);
                           
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
             
       SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String cbtext = String.valueOf(jComboBox2.getSelectedItem());
    
        
        
              
                InfoByMonth pnl = new InfoByMonth();
                      pnl.setVisible(true);
                       
                               
                      String year = cbtext;
                      pnl.jTextField1.setText(cbtext);        
                           
                      
                         String month = "Νοέμβριος";
                      pnl.jTextField2.setText(month);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            
       SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String cbtext = String.valueOf(jComboBox2.getSelectedItem());
    
        
        
              
                InfoByMonth pnl = new InfoByMonth();
                      pnl.setVisible(true);
                       
                               
                      String year = cbtext;
                      pnl.jTextField1.setText(cbtext);    
                      
                      String month = "Μάρτιος";
                      pnl.jTextField2.setText(month);
                      
                       
                           
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
             
       SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String cbtext = String.valueOf(jComboBox2.getSelectedItem());
    
        
        
              
                InfoByMonth pnl = new InfoByMonth();
                      pnl.setVisible(true);
                       
                               
                      String month = "Απρίλιος";
                      pnl.jTextField2.setText(month);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
            
       SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String cbtext = String.valueOf(jComboBox2.getSelectedItem());
    
        
        
              
                InfoByMonth pnl = new InfoByMonth();
                      pnl.setVisible(true);
                       
                               
                      String year = cbtext;
                      pnl.jTextField1.setText(cbtext); 
                      
                         String month = "Ιούνιος";
                      pnl.jTextField2.setText(month);
                           
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
            
       SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String cbtext = String.valueOf(jComboBox2.getSelectedItem());
    
        
        
              
                InfoByMonth pnl = new InfoByMonth();
                      pnl.setVisible(true);
                       
                               
                      String year = cbtext;
                      pnl.jTextField1.setText(cbtext);      
                      
                      
                         String month = "Ιούλιος";
                      pnl.jTextField2.setText(month);
                           
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
            
       SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String cbtext = String.valueOf(jComboBox2.getSelectedItem());
    
        
        
              
                InfoByMonth pnl = new InfoByMonth();
                      pnl.setVisible(true);
                       
                               
                      String year = cbtext;
                      pnl.jTextField1.setText(cbtext);        
                           
                      
                      
                         String month = "Αύγουστος";
                      pnl.jTextField2.setText(month);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
             
       SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String cbtext = String.valueOf(jComboBox2.getSelectedItem());
    
        
        
              
                InfoByMonth pnl = new InfoByMonth();
                      pnl.setVisible(true);
                       
                               
                      String year = cbtext;
                      pnl.jTextField1.setText(cbtext);        
                           
                      
                         String month = "Οκτώβριος";
                      pnl.jTextField2.setText(month);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
          
       SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String cbtext = String.valueOf(jComboBox2.getSelectedItem());
    
        
        
              
                InfoByMonth pnl = new InfoByMonth();
                      pnl.setVisible(true);
                       
                               
                      String year = cbtext;
                           
                      
                      
                         String month = "Δεκέμβριος";
                      pnl.jTextField2.setText(month);
                           
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataDisplaybyMonth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataDisplaybyMonth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataDisplaybyMonth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataDisplaybyMonth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataDisplaybyMonth().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
