/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg3hge;

import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.PageSize;
import java.awt.Color;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;



/**
 *
 * @author Giorg
 */
public class DisplayStatistics extends javax.swing.JFrame {
    
 
    
    public DisplayStatistics() throws ParseException, IOException {
        initComponents();
          this.getContentPane().setBackground(new Color(0x123456));
        ImageIcon image = new ImageIcon("src/opap.jpg");
        this.setIconImage(image.getImage());
       this.setLocationRelativeTo(null);
       this.setTitle("Προβολή στατιστικών δεδομένων ΤΖΟΚΕΡ");
       opapStats(5104);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Στατιστικά Δεδομένα ΤΖΟΚΕΡ 01/01/2000 - Σήμερα");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Εκτύπωση σε PDF");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pdf.png"))); // NOI18N
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graf.png"))); // NOI18N
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Προβολή Στατιστικών Στοιχείων Αποθηκευμένων Κληρώσεων σε Γραφική Μορφή");

        jTable1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);

        jTable2.setBackground(new java.awt.Color(255, 255, 255));
        jTable2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTable2.setForeground(new java.awt.Color(217, 158, 21));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"
            }
        ));
        jTable2.setRowHeight(28);
        jTable2.setRowMargin(2);
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Αριθμοί Πεντάδας");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Αριθμοί");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Καθυστερήσεις");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Εμφανίσεις");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Εμφανίσεις");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Καθυστερήσεις");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Αριθμοί");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ΤΖΟΚΕΡ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(623, 623, 623)
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(213, 213, 213)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(199, 199, 199)
                                        .addComponent(jButton3))
                                    .addComponent(jLabel6))
                                .addGap(530, 530, 530))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1391, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addGap(120, 120, 120))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(112, 112, 112)))
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       

        StatisticsGraphic graph = new StatisticsGraphic();
        graph.setVisible(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
       
        try {
            
        
                 Document document = new Document();
                 document.setPageSize(PageSize.A3.rotate());
            
             
            OutputStream stream = new FileOutputStream(new File("Stats.pdf"));
            
               PdfWriter.getInstance (document, stream);
               
                      document.open();
                      
               
               PdfPTable table5num = new PdfPTable(jTable1.getColumnCount()); 
                     table5num.setWidthPercentage(100);
               PdfPTable tableJok = new PdfPTable(jTable2.getColumnCount());
               
             /*  PdfPCell textcell = new PdfPCell(new Paragraph("5 Column Numbers "));
               table5num.addCell(textcell);*/
               for (int i = 0; i < 45; i++) {
                PdfPCell cel = new PdfPCell(new Paragraph(jTable1.getColumnName(i)));
                table5num.addCell(cel);
                
            }
               
               
               for (int rows = 0; rows < 2; rows++) {
                for (int cols = 0; cols < 45; cols++) {
                    table5num.addCell(jTable1.getModel().getValueAt(rows, cols).toString());
                }
            }
               
                 
                   
               for (int i = 0; i < 20; i++) {
                PdfPCell cel = new PdfPCell(new Paragraph(jTable2.getColumnName(i)));
                tableJok.addCell(cel);
            }
               
                for (int rows = 0; rows < 2; rows++) {
                for (int cols = 0; cols < 20; cols++) {
                    tableJok.addCell(jTable2.getModel().getValueAt(rows, cols).toString());
                }
            }
               
               
               
         Paragraph title = new Paragraph("Printed Report: Number, Delays, Appearances");
         
         Paragraph numname = new Paragraph("5 Numbers");
         Paragraph jok = new Paragraph("JOKER");
         
         numname.setAlignment(Element.ALIGN_CENTER);
        jok.setAlignment(Element.ALIGN_CENTER);
            document.add(title);
               document.add(Chunk.NEWLINE);
               document.add(Chunk.NEWLINE);
                 document.add(Chunk.NEWLINE);
               document.add(Chunk.NEWLINE);
               document.add(numname);
                  document.add(Chunk.NEWLINE);
            document.add(table5num);
            document.add(Chunk.NEWLINE);
            document.add(Chunk.NEWLINE);
                       document.add(Chunk.NEWLINE);
               document.add(Chunk.NEWLINE);
                    document.add(jok);
               document.add(Chunk.NEWLINE);
                  document.add(Chunk.NEWLINE);
            document.add(tableJok);
           

          
            File displayfile = new File("Stats.pdf");
            Desktop.getDesktop().open(displayfile);
 
        
    
        
        document.close();
        stream.close();
        
    
        
        } catch (DocumentException | IOException ex) {
        }
       
     
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DisplayStatistics().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(DisplayStatistics.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(DisplayStatistics.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    
    
    
        public void opapStats(int gameId) throws ParseException, IOException {
            

        String urlStatistics = "https://api.opap.gr/games/v1.0/" + gameId + "/statistics";
        OkHttpClient client = new OkHttpClient();

        Request request = new Request.Builder().url(urlStatistics).build();

        try (Response response = client.newCall(request).execute()) {
            if (response.isSuccessful() && response.body() != null) {
                String responseString = response.body().string();
                JSONParser jsonparser = new JSONParser();
                Object mainObj = jsonparser.parse(responseString);
                JSONObject mainJSONObj = (JSONObject) mainObj;
                JSONObject header = (JSONObject) mainJSONObj.get("header");
                JSONArray numbers = (JSONArray) mainJSONObj.get("numbers");
                JSONArray bonusNumbers = (JSONArray) mainJSONObj.get("bonusNumbers");

                
                Long dateFrom = (Long) header.get("dateFrom");
                Long dateTo = (Long) header.get("dateTo");
                Long drawCount = (Long) header.get("drawCount");
                
               
                

                Date dateFromd = new Date(dateFrom * 1000);
                Date dateTod = new Date(dateTo * 1000);
                int drawCountint = drawCount.intValue();

                
                DefaultTableModel tblMod = (DefaultTableModel)jTable1.getModel();
              
                String[] occurences = new String[45];
                String[] numberDel = new String[45];
                //String[] numberNo = new String[45];
                
                for (int i = 0; i < 45; i++) {
                    
                    JSONObject numbersObj = (JSONObject) numbers.get(i);
                     occurences[i] = String.valueOf(numbersObj.get("occurrences"));
                    
                    numberDel[i] = String.valueOf(numbersObj.get("delays"));
                    //numberNo[i] = String.valueOf(numbersObj.get("number"));
                    
                    
                    
                        
                }
                
               
                 tblMod.addRow(numberDel);
                 tblMod.addRow(occurences);
               
               
                
                 String[] bonusNumberOcc = new String[45];
                String[] bonusNumberDel = new String[45];
               // String[] bonusNumberNo = new String[45];
        

                for (int i = 0; i < 20; i++) {
                    JSONObject bonusNumbersObj = (JSONObject) bonusNumbers.get(i);
                    bonusNumberOcc[i] = String.valueOf(bonusNumbersObj.get("occurrences"));
                     bonusNumberDel[i] = String.valueOf(bonusNumbersObj.get("delays"));
                   //  bonusNumberNo[i] = String.valueOf(bonusNumbersObj.get("number"));
                   
                 }
                
                DefaultTableModel tblMod2 = (DefaultTableModel)jTable2.getModel();
                
                 tblMod2.addRow(bonusNumberDel);
                tblMod2.addRow(bonusNumberOcc);
               
              //  tblMod2.addRow(bonusNumberNo);
                
             
                 
                 
    
               
                    
                    
                
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    
    
    
    
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
